const albums = [
  {
    _id: "1",
    title: "Thriller",
    artist: "Michael Jackson",
    numberOfSongs: 9,
    image: require("../assets/images/artist2.webp"),
    duration: "42:19",
    year: 2023,
  },
  {
    _id: "2",
    title: "The Dark Side of the Moon",
    artist: "Pink Floyd",
    numberOfSongs: 10,
    image: require("../assets/images/artist1.webp"),
    duration: "42:49",
    year: 2023,
  },
  {
    _id: "3",
    title: "Nevermind",
    artist: "Nirvana",
    numberOfSongs: 12,
    image: require("../assets/images/artist7.webp"),
    duration: "49:15",
    year: 2023,
  },
  {
    _id: "4",
    title: "Abbey Road",
    artist: "The Beatles",
    numberOfSongs: 17,
    image: require("../assets/images/artist6.webp"),
    duration: "47:00",
    year: 2023,
  },
  {
    _id: "5",
    title: "Back in Black",
    artist: "AC/DC",
    numberOfSongs: 10,
    image: require("../assets/images/artist5.webp"),
    duration: "42:11",
    year: 2023,
  },
  {
    _id: "6",
    title: "Appetite for Destruction",
    artist: "Guns N' Roses",
    numberOfSongs: 12,
    image: require("../assets/images/artist4.webp"),
    duration: "53:51",
    year: 2023,
  },
  {
    _id: "7",
    title: "The Joshua Tree",
    artist: "U2",
    numberOfSongs: 11,
    image: require("../assets/images/artist3.webp"),
    duration: "50:13",
    year: 2023,
  },
  {
    _id: "8",
    title: "Born in the U.S.A.",
    artist: "Bruce Springsteen",
    numberOfSongs: 12,
    image: require("../assets/images/artist3.webp"),
    duration: "46:57",
    year: 2023,
  },
  {
    _id: "9",
    title: "Hysteria",
    artist: "Def Leppard",
    numberOfSongs: 12,
    image: require("../assets/images/artist2.webp"),
    duration: "62:32",
    year: 2023,
  },
  {
    _id: "10",
    title: "Bad",
    artist: "Michael Jackson",
    numberOfSongs: 11,
    image: require("../assets/images/artist1.webp"),
    duration: "48:16",
    year: 2023,
  },
  {
    _id: "11",
    title: "Ten",
    artist: "Pearl Jam",
    numberOfSongs: 11,
    image: require("../assets/images/artist3.webp"),
    duration: "99:32",
    year: 2023,
  }
];

export default albums;
